# Generated by Django 3.2.6 on 2022-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='count',
            field=models.PositiveIntegerField(default=0, max_length=14, verbose_name='Колличество проведенных заявок'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fixed_pay',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Фиксированная заработная плата'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Процент'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='Статус доступ закрыт/открыт'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_group',
            field=models.CharField(blank=True, choices=[('admin', 'Руководитель/Администратор'), ('operator', 'Оператор'), ('finance', 'Финансист')], max_length=255, null=True, verbose_name='Группа пользователей'),
        ),
    ]
