# Generated by Django 3.2.6 on 2022-03-24 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время авторизации пользователя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='logout_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время выхода пользователя'),
        ),
        migrations.CreateModel(
            name='TimeManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('login_time', models.DateTimeField(auto_now=True, verbose_name='Время авторизации пользователя')),
                ('logout_time', models.DateTimeField(auto_now=True, verbose_name='Время выхода пользователя')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
