# Generated by Django 3.2.6 on 2022-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220324_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemanage',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время авторизации пользователя'),
        ),
    ]
