# Generated by Django 3.2.6 on 2022-04-29 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='logout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 17, 42, 58, 860236, tzinfo=utc), verbose_name='Время выхода пользователя'),
        ),
        migrations.AlterField(
            model_name='timemanage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timemanage',
            name='logout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 17, 42, 58, 861874, tzinfo=utc), verbose_name='Время выхода пользователя'),
        ),
    ]
