# Generated by Django 3.2.6 on 2022-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220429_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fixed_pay',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='logout_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='personal_post',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_group',
            field=models.CharField(blank=True, choices=[('director', 'Директор'), ('worker', 'Работник')], max_length=255, null=True, verbose_name='Группа пользователей'),
        ),
        migrations.DeleteModel(
            name='TimeManage',
        ),
    ]
