# Generated by Django 3.2.6 on 2022-05-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220520_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО пользователя'),
        ),
    ]
