# Generated by Django 3.2.6 on 2022-05-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_fio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fio',
        ),
    ]
